Repository TEAM-DHS/dhs-frontend, pull requests merged in 2023-11, with the labels that each got.

#1 [Feature] 네비게이션 바, 홈페이지 인기 TOP5 퍼블리싱
  .gitignore
  .prettierrc.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/assets/logo.svg
  src/components/DetailPage/test.txt
  src/components/HomePage/ProgressProvider.ts
  src/components/HomePage/TopFive.tsx
  src/components/_common/NavBar.tsx
  src/custom.d.ts
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/HomePage.tsx
  src/pages/ListPage.tsx
  src/react-app-env.d.ts
  src/services/api/test.txt
  src/services/store/auth.ts
  src/setupTests.ts
  src/styles/swiper.css
  src/styles/tailwind.css
  src/tailwind.css
  src/utils/@types/event.d.ts
  src/utils/data/categoryData.ts
  src/utils/data/topfiveData.ts
  src/utils/hooks/test.txt
  tailwind.config.js
  tsconfig.json
Labels: enhancement

#3 [Feature] 공용 컴포넌트 EventItem, CategoryBlock 구현
  src/assets/My/arrow_circle_right.svg
  src/assets/heart.svg
  src/components/HomePage/ListSection.tsx
  src/components/HomePage/SearchSection.tsx
  src/components/_common/CategoryBlock.tsx
  src/components/_common/EventItem.tsx
  src/components/_common/NavBar.tsx
  src/pages/HomePage.tsx
  src/services/store/event.ts
  src/utils/@types/event.d.ts
  src/utils/data/categoryData.ts
  src/utils/data/eventData.ts
  tailwind.config.js
Labels: enhancement

#4 [Feature] 신청자 리스트 조회 페이지 퍼블리싱
  src/App.tsx
  src/components/LoginPage/Button.tsx
  src/components/LoginPage/Decoration.tsx
  src/components/LoginPage/LoginSection.tsx
  src/components/LoginPage/MainCopy.tsx
  src/components/LoginPage/Navigate.tsx
  src/components/LoginPage/Template.tsx
  src/components/MyPage/CreatedList.tsx
  src/components/MyPage/EmptyMessage.tsx
  src/components/MyPage/Header.tsx
  src/components/MyPage/LikedList.tsx
  src/components/MyPage/RegisteredList.tsx
  src/components/RegisterList/CloseButton.tsx
  src/components/RegisterList/CloseModal.tsx
  src/components/RegisterList/List.tsx
  src/components/RegisterList/Table.tsx
  src/components/SignUpPage/PasswordReInput.tsx
  src/components/SignUpPage/SignUpSection.tsx
  src/components/_common/EventItem.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPages.tsx
  src/pages/RegisterListPage.tsx
  src/pages/SignUpPage.tsx
  src/utils/data/registerData.ts
  tailwind.config.js
Labels: enhancement

#6 [Feature] 행사 등록 페이지 퍼블리싱
  src/App.tsx
  src/components/CreatedPage/Bank.tsx
  src/components/CreatedPage/Category.tsx
  src/components/CreatedPage/Description.tsx
  src/components/CreatedPage/EndDate.tsx
  src/components/CreatedPage/EventTitle.tsx
  src/components/CreatedPage/Introduction.tsx
  src/components/CreatedPage/People.tsx
  src/components/CreatedPage/PersonalInfo.tsx
  src/components/CreatedPage/Photos.tsx
  src/components/CreatedPage/Place.tsx
  src/components/CreatedPage/Price.tsx
  src/components/CreatedPage/Question.tsx
  src/components/CreatedPage/SearchForm.tsx
  src/components/CreatedPage/TeamIntro.tsx
  src/components/CreatedPage/TeamName.tsx
  src/components/CreatedPage/Thumbnail.tsx
  src/components/MyPage/Header.tsx
  src/components/_common/CategoryNavBar.tsx
  src/pages/CreatedPage.tsx
Labels: enhancement

#7 [Feature] 행사 신청 페이지, 행사 상세 페이지 퍼블리싱
  package-lock.json
  package.json
  public/favicon/android-chrome-192x192.png
  public/favicon/android-chrome-512x512.png
  public/favicon/apple-touch-icon.png
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/manifest.json
  public/index.html
  src/assets/Detail/arrow.svg
  src/assets/Detail/line_arrow.svg
  src/assets/Detail/location.svg
  src/assets/Detail/notice.svg
  src/assets/Detail/pin.svg
  src/components/DetailPage/InfoSection.tsx
  src/components/DetailPage/LocationTab.tsx
  src/components/DetailPage/NoticeModal.tsx
  src/components/DetailPage/NoticeTab.tsx
  src/components/DetailPage/OtherSection.tsx
  src/components/DetailPage/PlanTab.tsx
  src/components/DetailPage/TabSection.tsx
  src/components/DetailPage/test.txt
  src/components/HomePage/TopFive.tsx
  src/components/ListPage/CategoryBar.tsx
  src/components/ListPage/ListSection.tsx
  src/components/RegisterPage/FormSection.tsx
  src/components/RegisterPage/InfoSection.tsx
  src/components/_common/CategoryBlock.tsx
  src/components/_common/CategoryNavBar.tsx
  src/components/_common/EventItem.tsx
  src/components/_common/Modal.tsx
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/RegisterPage.tsx
  src/services/store/event.ts
  src/styles/navbar.css
  src/styles/registerform.css
  src/styles/swiper.css
  src/utils/@types/event.d.ts
  src/utils/data/eventData.ts
  src/utils/data/filterData.ts
  src/utils/data/topfiveData.ts
  src/utils/hooks/test.txt
  src/utils/hooks/useCategoryText.ts
  src/utils/hooks/useParagraph.tsx
  tailwind.config.js
Labels: enhancement, question

#8 [Fix] 행사 상세 페이지 반응형 수정 & 공지 수정 모달 미완성 UI 수정
  src/components/DetailPage/InfoSection.tsx
  src/components/DetailPage/NoticeModal.tsx
  src/components/DetailPage/PlanTab.tsx
  tailwind.config.js
Labels: enhancement

#9 [Feature] 회원가입, 로그인 api 연결
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/client.ts
  src/components/LoginPage/Button.tsx
  src/components/LoginPage/IdInput.tsx
  src/components/LoginPage/LoginSection.tsx
  src/components/LoginPage/PasswordInput.tsx
  src/components/SignUpPage/PasswordReInput.tsx
  src/components/SignUpPage/SignUpSection.tsx
  src/utils/constants/errorMessage.ts
Labels: enhancement

#10 [Feature] 카카오 로그인, 로그아웃 기능 구현
  src/App.tsx
  src/api/auth.ts
  src/assets/Login/loading.gif
  src/components/CreatedPage/Question.tsx
  src/components/LoginPage/Button.tsx
  src/components/LoginPage/LoginSection.tsx
  src/components/MyPage/Header.tsx
  src/components/SignUpPage/SignUpSection.tsx
  src/pages/LoadingPage.tsx
  src/services/store/auth.ts
Labels: enhancement

#13 [Fix] 행사 관련 API 2차 연결 (테스트 완료)
  src/api/heart.ts
  src/api/program.ts
  src/components/DetailPage/InfoSection.tsx
  src/components/DetailPage/NoticeModal.tsx
  src/components/DetailPage/NoticeTab.tsx
  src/components/DetailPage/PlanTab.tsx
  src/components/HomePage/ListSection.tsx
  src/components/HomePage/TopFive.tsx
  src/components/ListPage/CategoryBar.tsx
  src/components/ListPage/SortBar.tsx
  src/components/_common/EventItem.tsx
  src/utils/@types/event.d.ts
  src/utils/data/topfiveData.ts
  src/utils/hooks/useHeart.ts
  src/utils/hooks/useInfiniteScroll.ts
  src/utils/hooks/useParagraph.tsx
Labels: enhancement

#15 [Fix] refresh token 재발급 오류 해결
  src/api/auth.ts
  src/api/heart.ts
  src/api/index.ts
  src/api/program.ts
  src/components/CreatedPage/Photos.tsx
  src/components/CreatedPage/Price.tsx
  src/components/CreatedPage/SearchForm.tsx
  src/components/CreatedPage/Thumbnail.tsx
  src/components/MyPage/CreatedList.tsx
Labels: bug

#16 [Feature] 행사 등록 api 연결
  src/api/auth.ts
  src/api/index.ts
  src/api/program.ts
  src/api/refreshtoken.ts
  src/components/CreatedPage/Bank.tsx
  src/components/CreatedPage/Category.tsx
  src/components/CreatedPage/Description.tsx
  src/components/CreatedPage/EndDate.tsx
  src/components/CreatedPage/EventDate.tsx
  src/components/CreatedPage/EventTitle.tsx
  src/components/CreatedPage/People.tsx
  src/components/CreatedPage/PersonalInfo.tsx
  src/components/CreatedPage/Photos.tsx
  src/components/CreatedPage/Place.tsx
  src/components/CreatedPage/Price.tsx
  src/components/CreatedPage/Question.tsx
  src/components/CreatedPage/SearchForm.tsx
  src/components/CreatedPage/TeamIntro.tsx
  src/components/CreatedPage/TeamName.tsx
  src/components/CreatedPage/Thumbnail.tsx
  src/components/DetailPage/InfoSection.tsx
  src/components/DetailPage/NoticeModal.tsx
  src/components/DetailPage/NoticeTab.tsx
  src/components/DetailPage/TabSection.tsx
  src/components/HomePage/ListSection.tsx
  src/components/ListPage/CategoryBar.tsx
  src/components/LoginPage/Button.tsx
  src/components/LoginPage/IdInput.tsx
  src/components/LoginPage/LoginSection.tsx
  src/components/LoginPage/Navigate.tsx
  src/components/LoginPage/PasswordInput.tsx
  src/components/LoginPage/Template.tsx
  src/components/MyPage/EmptyMessage.tsx
  src/components/MyPage/Header.tsx
  src/components/MyPage/PageNation.tsx
  src/components/RegisterList/CloseButton.tsx
  src/components/RegisterList/CloseModal.tsx
  src/components/RegisterList/List.tsx
  src/components/RegisterList/Table.tsx
  src/components/SignUpPage/PasswordReInput.tsx
  src/components/_common/EventItem.tsx
  src/utils/@types/event.d.ts
Labels: enhancement

#17 [Chore] 배포를 위한 develop -> main merge
  src/api/auth.ts
  src/api/heart.ts
  src/api/index.ts
  src/api/program.ts
  src/api/refreshtoken.ts
  src/components/CreatedPage/Bank.tsx
  src/components/CreatedPage/Category.tsx
  src/components/CreatedPage/Description.tsx
  src/components/CreatedPage/EndDate.tsx
  src/components/CreatedPage/EventDate.tsx
  src/components/CreatedPage/EventTitle.tsx
  src/components/CreatedPage/People.tsx
  src/components/CreatedPage/PersonalInfo.tsx
  src/components/CreatedPage/Photos.tsx
  src/components/CreatedPage/Place.tsx
  src/components/CreatedPage/Price.tsx
  src/components/CreatedPage/Question.tsx
  src/components/CreatedPage/SearchForm.tsx
  src/components/CreatedPage/TeamIntro.tsx
  src/components/CreatedPage/TeamName.tsx
  src/components/CreatedPage/Thumbnail.tsx
  src/components/DetailPage/InfoSection.tsx
  src/components/DetailPage/NoticeModal.tsx
  src/components/DetailPage/NoticeTab.tsx
  src/components/DetailPage/TabSection.tsx
  src/components/HomePage/ListSection.tsx
  src/components/ListPage/CategoryBar.tsx
  src/components/LoginPage/Button.tsx
  src/components/LoginPage/IdInput.tsx
  src/components/LoginPage/LoginSection.tsx
  src/components/LoginPage/Navigate.tsx
  src/components/LoginPage/PasswordInput.tsx
  src/components/LoginPage/Template.tsx
  src/components/MyPage/CreatedList.tsx
  src/components/MyPage/EmptyMessage.tsx
  src/components/MyPage/Header.tsx
  src/components/MyPage/PageNation.tsx
  src/components/RegisterList/CloseButton.tsx
  src/components/RegisterList/CloseModal.tsx
  src/components/RegisterList/List.tsx
  src/components/RegisterList/Table.tsx
  src/components/SignUpPage/PasswordReInput.tsx
  src/components/_common/EventItem.tsx
  src/utils/@types/event.d.ts
Labels: documentation

#18 [Chore] build 파일 추가
  build.sh
Labels: documentation

#19 [Fix] 행사 상세 페이지 이슈 및 버그 수정
  .github/workflows/main.yml
  build.sh
  src/components/DetailPage/InfoSection.tsx
  src/components/DetailPage/NoticeModal.tsx
  src/components/DetailPage/NoticeTab.tsx
  src/components/DetailPage/PlanTab.tsx
  src/components/_common/EventItem.tsx
  src/pages/DetailPage.tsx
  src/pages/MyPages.tsx
  src/services/store/event.ts
  src/utils/hooks/useHeart.ts
Labels: enhancement

#20 [Chore] 배포를 위한 develop -> main merge
  src/components/DetailPage/InfoSection.tsx
  src/components/DetailPage/NoticeModal.tsx
  src/components/DetailPage/NoticeTab.tsx
  src/components/DetailPage/PlanTab.tsx
  src/components/_common/EventItem.tsx
  src/pages/DetailPage.tsx
  src/pages/MyPages.tsx
  src/services/store/event.ts
  src/utils/hooks/useHeart.ts
Labels: documentation

#21 [Fix] 행사 상세페이지 좋아요 버그 수정
  src/components/DetailPage/InfoSection.tsx
  src/components/_common/EventItem.tsx
  src/pages/DetailPage.tsx
  src/utils/hooks/useHeart.ts
Labels: enhancement

#23 [Fix] 신청자 목록 인원 누락 해결
  src/components/RegisterList/Table.tsx
  src/components/_common/EventItem.tsx
  src/pages/RegisterListPage.tsx
  src/utils/@types/event.d.ts
Labels: bug

#22 [Chore] 배포를 위한 develop -> main merge
  src/components/DetailPage/InfoSection.tsx
  src/components/_common/EventItem.tsx
  src/pages/DetailPage.tsx
  src/utils/hooks/useHeart.ts
Labels: documentation

#24 [Fix] 파일 용량 클 경우 예외처리
  src/components/CreatedPage/SearchForm.tsx
  src/components/RegisterList/Table.tsx
  src/components/_common/EventItem.tsx
  src/pages/RegisterListPage.tsx
  src/utils/@types/event.d.ts
Labels: bug
